### ISSUE TITLE
Easier argument passing

### ISSUE THREAD

**Issue by alphapapa** [cyrus-and/trace#2]
Taking an example from the readme:

```
trace -d -mread_b -mwrite_b -- attach $(pidof cp)
```

It would be much nicer if you could write this as:

```
trace -d -m read_b write_b -- attach $(pidof cp)
```

**Comment by cyrus-and** [comment]
The fact is that order matters for metrics and the latter notation doesn't play nice with mixed metric types:

```
trace -d -mtotal_mem_kb -x'ts date +%s' -mcpu_load_perc -- run sleep 5
```
